prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
prefix meta: <http://kerndatensatz-forschung.de/owl/Meta#>
prefix dct: <http://purl.org/dc/terms/>
prefix owl: <http://www.w3.org/2002/07/owl#>
prefix status: <http://www.w3.org/2003/06/sw-vocab-status/ns#>
prefix skos: <http://www.w3.org/2004/02/skos/core#>
prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>
prefix dce: <http://purl.org/dc/elements/1.1/>

SELECT DISTINCT ?s ?type ?parent ?label ?definition ?domain ?range ?version ?status ?notes
WHERE {
   ?s a ?type .
   
   OPTIONAL {
       ?s terms:hasVersion ?version .
   }
   OPTIONAL {
       ?s skos:definition ?definition .
   }
   OPTIONAL {
       ?s rdfs:range ?range .
   }
   OPTIONAL {
       ?s rdfs:domain ?domain .
   }
   OPTIONAL {
       ?s skos:scopeNote ?notes
   }
   OPTIONAL {
       ?s ns:term_status ?status .
   }
   OPTIONAL {
       ?s rdfs:subClassOf ?parent .
   }
   OPTIONAL {
       ?s rdfs:label ?label .
       FILTER (lang(?label) = "de")
   }
   FILTER (!isBlank(?s))
}